namespace AIDA64
{
    [bindable]
    [default_interface]
    runtimeclass CpuModel
    {
        CpuModel();

        String Name;
        String Manufacturer;
        String Id;

        UInt32 CoreCount;
        UInt32 MaxClockSpeed;
        UInt32 CurrentClockSpeed;

        UInt16 LoadPercentage;
        UInt16 Architecture;
        UInt16 AddressWidth;
        UInt16 DataWidth;

        String DeviceId;
        String Caption;
        String Description;

        UInt32 NumberOfLogicalProcessors;
        UInt32 L2CacheSize;
        UInt32 L3CacheSize;

        UInt16 Revision;
        UInt16 Stepping;
        UInt16 Family;
        UInt16 CurrentVoltage;
    }
}
