namespace AIDA64
{
    [default_interface]
    runtimeclass Graph : Microsoft.UI.Xaml.Controls.UserControl
    {
        Graph();

        static Microsoft.UI.Xaml.DependencyProperty TitleTextProperty { get; };
        static Microsoft.UI.Xaml.DependencyProperty DefaultColorProperty { get; };

        Windows.Foundation.Collections.IObservableVector<Double> Points;
        Windows.UI.Color DefaultColor;

        String TitleText;


        void Pause();
        void Error();
    }
}
