namespace AIDA64
{
    [default_interface]
    runtimeclass Graph : Microsoft.UI.Xaml.Controls.UserControl
    {
        Graph();

        static Microsoft.UI.Xaml.DependencyProperty PointsProperty { get; };
        static Microsoft.UI.Xaml.DependencyProperty TitleTextProperty { get; };
        static Microsoft.UI.Xaml.DependencyProperty DefaultColorProperty { get; };
        Windows.Foundation.Collections.IVectorView<Windows.Foundation.Point> Points;
        String TitleText;
        Windows.UI.Color DefaultColor;

        void SetTotal(UInt64 bytes);
        void SetPoints(Windows.Foundation.Collections.IVectorView<Windows.Foundation.Point> points);
        void AddPoint(Windows.Foundation.Point point);

        void Pause();
        void Error();
    }
}
