import "ViewModels/MainViewModel.idl";

namespace AIDA64
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
        MainViewModel MainViewModel{ get; };
    }
}
