import "Models/ChatMessage.idl";

namespace AIDA64
{
    [bindable]
    [default_interface]
    runtimeclass AiPageViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        AiPageViewModel();
        Microsoft.UI.Xaml.Input.ICommand SendRequest { get; };
        Windows.Foundation.Collections.IObservableVector<ChatMessage> Messages;
        String ResponseMessage;
        String RequestMessage;
    }
}
