import "Models/CpuModel.idl";

namespace AIDA64
{
    [bindable]
    [default_interface]
    runtimeclass CpuPageViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        CpuPageViewModel();
        CpuModel CpuModel;
        Windows.Foundation.Collections.IObservableVector<Double> Values;
        Microsoft.UI.Xaml.Input.ICommand TESTA { get; };
    }
}
