import "Models/DisplayModel.idl";

namespace AIDA64
{
    [bindable]
    [default_interface]
    runtimeclass DisplayPageViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        DisplayPageViewModel();
        DisplayModel DisplayModel;

        void Activate();
    }
}
